### ISSUE TITLE
Add ability to exclude additional words on a per-project basis

### ISSUE THREAD

**Issue by nickfz3n** [zendesk/term-check#41]
https://github.com/zendesk/term-check/pull/18 added the ability to ignore certain terms from being flagged. Adding the ability to allow a repo to define additional words to be flagged would bring balance.

(If something like this is already supported, then documentation on how to do this should be added)

Example of how it could be defined, styled after the README config example:

```yaml
# An array of patterns following .gitignore rules (http://git-scm.com/docs/gitignore) specifying which files and
# directories should be ignored by the app
ignore:
  - foo
  - bar/
add:
  - <term you wish to block in your repo>
  - <another term>
```
